export const exchanges = [
  { name: 'Binance', detail: { en: 'Primary source of current historical-data research', ko: '현재 역사 데이터 연구의 주요 출처' }, href: 'https://accounts.binance.com/register?ref=V5EBF1SH' },
  { name: 'Bybit', detail: { en: 'Digital-asset derivatives platform', ko: '디지털 자산 파생상품 플랫폼' }, href: 'https://partner.bybit.com/b/skrrrr' },
  { name: 'OKX', detail: { en: 'Digital-asset trading platform', ko: '디지털 자산 거래 플랫폼' }, href: 'https://www.okx.com/join/SKRRRR' },
  { name: 'Bitget', detail: { en: 'Digital-asset trading platform', ko: '디지털 자산 거래 플랫폼' }, href: 'https://partner.bitget.com/bg/5krrrr' },
];

const nav = {
  en: [
    { href: '#status', label: 'Research' },
    { href: '#process', label: 'Process' },
    { href: '#platforms', label: 'Platforms' },
    { href: '#about', label: 'About' },
  ],
  ko: [
    { href: '#status', label: '연구 현황' },
    { href: '#process', label: '연구 과정' },
    { href: '#platforms', label: '플랫폼' },
    { href: '#about', label: '소개' },
  ],
};

const common = {
  contactEmail: 'alpha@skrrrrlabs.com',
  contactHandle: '@skrrrrlabs',
  platforms: exchanges.map((exchange) => ({ ...exchange, detail: exchange.detail.en })),
};

export const copy = {
  en: {
    ...common,
    metaTitle: 'SkrrrrLabs — Independent Market Structure Research',
    metaDescription: 'Independent market-structure research focused on historical data, systematic backtesting and repeatable trading frameworks across digital assets and global derivatives.',
    nav: nav.en,
    heroEyebrow: 'MARKET STRUCTURE · DATA · SYSTEMATIC RESEARCH',
    heroTitle: 'Structure Before Prediction.',
    heroBody: 'SkrrrrLabs is an independent market-research project focused on transforming historical market data into structured, testable trading frameworks.',
    heroBodySecondary: 'Current validation uses approximately 600GB of selected Binance historical data from the post-Ethereum ETF approval market regime.',
    researchCta: 'Explore the Research Process',
    platformsCta: 'Trading Platforms',
    collaborationCta: 'Discuss a Collaboration',
    pipeline: ['RAW DATA', 'SELECTION', 'NORMALIZATION', 'BACKTESTING', 'VALIDATION'],
    statusLabel: 'CURRENT RESEARCH',
    statusTitle: 'A filtered dataset, not a larger claim.',
    statusIntro: 'The original archive contains approximately 1TB of Binance historical market data. Around 400GB is classified as legacy data from the pre-Ethereum ETF approval period and excluded from active validation. The working dataset contains approximately 600GB of selected post-approval market data used to study the current market regime.',
    statusNote: 'No strategy is presented as validated until it survives testing across structure, volatility, time, adverse movement and execution conditions.',
    metrics: [
      { value: '≈1TB', label: 'Historical archive' },
      { value: '≈600GB', label: 'Selected active dataset' },
      { value: 'ACTIVE', label: 'Backtesting and validation' },
    ],
    statusRows: [
      ['Data ingestion', 'Complete'], ['Historical archiving', 'Complete'], ['Regime separation', 'Active'], ['Data validation', 'Active'], ['Strategy backtesting', 'In progress'], ['Execution testing', 'Not published'], ['Live system', 'Not deployed'],
    ],
    processLabel: 'RESEARCH PROCESS',
    processTitle: 'From raw data to a decision framework.',
    processIntro: 'Collecting more data does not create an edge by itself. The objective is to define comparable conditions, reject weak assumptions and convert surviving observations into repeatable processes.',
    process: [
      ['Define the regime', 'Separate structurally different market environments before testing.'],
      ['Build the dataset', 'Clean, align and normalize historical exchange data.'],
      ['Form the hypothesis', 'Specify structure, liquidity, volatility, time and invalidation conditions.'],
      ['Backtest', 'Measure outcomes, adverse movement, holding time and execution cost.'],
      ['Stress test', 'Test whether a result survives different instruments and market conditions.'],
      ['Validate or reject', 'Discard hypotheses when the evidence does not support them.'],
      ['Automate', 'Convert only repeatable and measurable processes into systems.'],
    ],
    marketsLabel: 'RESEARCH SCOPE',
    marketsTitle: 'Markets under observation.',
    marketsIntro: 'Digital assets remain the primary research focus. Other markets provide context for testing whether a framework travels beyond one instrument set.',
    markets: [
      { title: 'Digital Assets', description: 'Historical exchange data, derivatives structure, liquidity behavior and market-regime analysis.', primary: true },
      { title: 'NASDAQ', description: 'Index structure, volatility, macro conditions and derivatives behavior.' },
      { title: 'Gold', description: 'Dollar liquidity, real yields, defensive flows and structural price behavior.' },
    ],
    validationLabel: 'VALIDATION SCOPE',
    validationTitle: 'The goal is not to find a pattern that worked once.',
    validationIntro: 'The goal is to identify where, when and under what conditions it stops working.',
    validation: ['Structure', 'Invalidation', 'Time', 'Adverse movement', 'Execution conditions'],
    principlesLabel: 'PRINCIPLES',
    principlesTitle: 'Rules for staying honest.',
    principles: ['Data before belief.', 'Context before direction.', 'Survival before profit.', 'Probability before conviction.', 'Process before emotion.', 'Rejection before deployment.'],
    aboutLabel: 'ABOUT',
    aboutTitle: 'Independent by design.',
    aboutBody: ['SkrrrrLabs is an independent market-research project built around a simple belief: trading decisions should be tested before they are trusted.', 'The project began with digital-asset market data and is being developed into a broader research framework for crypto, index and metals trading.', 'Its current focus is historical-data validation, systematic backtesting and the design of repeatable decision processes.', 'SkrrrrLabs does not manage client capital, provide guaranteed trading signals or present unfinished research as proven performance.'],
    collaborationLabel: 'COLLABORATION',
    collaborationTitle: 'Good systems are rarely built from one discipline.',
    collaborationBody: 'SkrrrrLabs is open to thoughtful conversations with developers, data engineers, researchers and systematic traders working on market data, backtesting, execution infrastructure or research automation.',
    collaborationNote: 'No sales pitch is required. A clear problem, useful expertise or serious research question is enough.',
    collaborators: ['Python developers', 'Data engineers', 'Quantitative researchers', 'Systematic traders', 'Market-data infrastructure builders', 'Research partners'],
    startConversation: 'Start a Conversation',
    platformsLabel: 'TRADING PLATFORMS',
    platformsTitle: 'Research first. Execution second.',
    platformsIntro: 'SkrrrrLabs conducts independent market research. Trading execution is performed through external platforms.',
    openPlatform: 'Open platform',
    affiliateDisclosure: 'Some outbound links may be affiliate links and may support the continued development and operation of SkrrrrLabs at no additional cost to the user.',
    footerDescriptor: 'Independent Market Structure Research',
    footerStatement: 'SkrrrrLabs is an independent research project. Nothing on this website constitutes investment advice, financial advice or a guarantee of future performance.',
    footerLinks: { process: 'Research Process', status: 'Research Status', markets: 'Markets', about: 'About', collaboration: 'Collaboration', platforms: 'Trading Platforms', risk: 'Risk Disclosure', affiliate: 'Affiliate Disclosure', privacy: 'Privacy', terms: 'Terms', contact: 'Contact' },
  },
  ko: {
    ...common,
    metaTitle: 'SkrrrrLabs — 독립 시장 구조 연구',
    metaDescription: '디지털 자산과 글로벌 파생시장의 역사 데이터, 체계적 백테스트, 반복 가능한 트레이딩 프레임워크를 연구합니다.',
    nav: nav.ko,
    heroEyebrow: 'MARKET STRUCTURE · DATA · SYSTEMATIC RESEARCH',
    heroTitle: '예측보다 구조.',
    heroBody: 'SkrrrrLabs는 역사적 시장 데이터를 구조화되고 검증 가능한 트레이딩 프레임워크로 전환하는 독립 리서치 프로젝트입니다.',
    heroBodySecondary: '현재는 이더리움 현물 ETF 승인 이후 시장 국면의 바이낸스 선별 데이터 약 600GB를 검증하고 있습니다.',
    researchCta: '연구 과정 보기', platformsCta: '트레이딩 플랫폼', collaborationCta: '협업 문의',
    pipeline: ['RAW DATA', 'SELECTION', 'NORMALIZATION', 'BACKTESTING', 'VALIDATION'],
    statusLabel: 'CURRENT RESEARCH', statusTitle: '더 큰 숫자가 아닌, 선별된 데이터셋.',
    statusIntro: '기존 바이낸스 역사 데이터 아카이브는 약 1TB입니다. 이더리움 현물 ETF 승인 이전 국면의 약 400GB는 레거시 데이터로 분류해 현재 검증에서 제외했습니다. 현재 시장 국면을 연구하기 위해 승인 이후 선별한 약 600GB를 활용하고 있습니다.',
    statusNote: '구조, 변동성, 시간, 불리한 움직임, 실행 조건을 통과하기 전까지 어떤 전략도 검증된 것으로 제시하지 않습니다.',
    metrics: [{ value: '약 1TB', label: '역사 데이터 아카이브' }, { value: '약 600GB', label: '선별 활성 데이터셋' }, { value: 'ACTIVE', label: '백테스트 및 검증' }],
    statusRows: [['데이터 수집', '완료'], ['역사 데이터 보관', '완료'], ['시장 국면 분리', '진행 중'], ['데이터 검증', '진행 중'], ['전략 백테스트', '진행 중'], ['실행 테스트', '공개 전'], ['라이브 시스템', '미배포']],
    processLabel: 'RESEARCH PROCESS', processTitle: '원시 데이터에서 의사결정 체계까지.', processIntro: '데이터를 더 많이 모으는 것만으로 우위가 생기지는 않습니다. 비교 가능한 조건을 정의하고 약한 가정을 거부하며, 살아남은 관찰을 반복 가능한 과정으로 전환합니다.',
    process: [['시장 국면 정의', '구조적으로 다른 시장 환경을 분리한 뒤 테스트합니다.'], ['데이터셋 구축', '거래소 역사 데이터를 정제하고 정렬하며 정규화합니다.'], ['가설 수립', '구조, 유동성, 변동성, 시간, 무효화 조건을 명시합니다.'], ['백테스트', '결과, 불리한 움직임, 보유 시간, 실행 비용을 측정합니다.'], ['스트레스 테스트', '결과가 다른 상품과 시장 환경에서도 살아남는지 확인합니다.'], ['검증 또는 거부', '근거가 부족하면 가설을 폐기합니다.'], ['자동화', '반복 가능하고 측정 가능한 과정만 시스템으로 전환합니다.']],
    marketsLabel: 'RESEARCH SCOPE', marketsTitle: '관찰 중인 시장.', marketsIntro: '디지털 자산이 현재의 주요 연구 대상입니다. 다른 시장은 프레임워크가 하나의 상품군을 넘어 적용되는지 확인하는 맥락으로 활용합니다.', markets: [{ title: 'Digital Assets', description: '거래소 역사 데이터, 파생 구조, 유동성 행동과 시장 국면을 연구합니다.', primary: true }, { title: 'NASDAQ', description: '지수 구조, 변동성, 거시 조건과 파생상품 행동을 관찰합니다.' }, { title: 'Gold', description: '달러 유동성, 실질 금리, 방어적 자금 흐름과 가격 구조를 관찰합니다.' }],
    validationLabel: 'VALIDATION SCOPE', validationTitle: '한 번 작동한 패턴을 찾는 것이 목표가 아닙니다.', validationIntro: '언제, 어디서, 어떤 조건에서 작동을 멈추는지 확인하는 것이 목표입니다.', validation: ['구조', '무효화', '시간', '불리한 움직임', '실행 조건'],
    principlesLabel: 'PRINCIPLES', principlesTitle: '정직한 연구를 위한 원칙.', principles: ['데이터가 믿음보다 먼저입니다.', '방향보다 맥락이 먼저입니다.', '수익보다 생존이 먼저입니다.', '확신보다 확률이 먼저입니다.', '감정보다 과정이 먼저입니다.', '배포보다 거부가 먼저입니다.'],
    aboutLabel: 'ABOUT', aboutTitle: '독립적으로 설계합니다.', aboutBody: ['SkrrrrLabs는 트레이딩 의사결정은 신뢰하기 전에 먼저 테스트해야 한다는 믿음에서 시작한 독립 리서치 프로젝트입니다.', '디지털 자산 데이터에서 시작해 암호화폐, 지수, 금속 시장을 아우르는 연구 프레임워크로 확장하고 있습니다.', '현재는 역사 데이터 검증, 체계적 백테스트, 반복 가능한 의사결정 과정 설계에 집중합니다.', '고객 자금을 운용하거나 보장된 신호를 제공하지 않으며, 미완성 연구를 검증된 성과로 제시하지 않습니다.'],
    collaborationLabel: 'COLLABORATION', collaborationTitle: '좋은 시스템은 하나의 분야만으로 만들어지지 않습니다.', collaborationBody: '시장 데이터, 백테스트, 실행 인프라, 리서치 자동화에 관심 있는 개발자, 데이터 엔지니어, 연구자, 시스템 트레이더와의 대화를 환영합니다.', collaborationNote: '영업 제안은 필요하지 않습니다. 명확한 문제, 유용한 전문성, 진지한 연구 질문이면 충분합니다.', collaborators: ['Python 개발자', '데이터 엔지니어', '퀀트 연구자', '시스템 트레이더', '시장 데이터 인프라 빌더', '리서치 파트너'], startConversation: '대화 시작하기',
    platformsLabel: 'TRADING PLATFORMS', platformsTitle: '연구가 먼저, 실행은 그 다음입니다.', platformsIntro: 'SkrrrrLabs는 독립적으로 시장을 연구합니다. 거래 실행은 외부 플랫폼에서 이루어집니다.', openPlatform: '플랫폼 열기', affiliateDisclosure: '일부 외부 링크는 제휴 링크일 수 있으며 사용자에게 추가 비용 없이 SkrrrrLabs의 개발과 운영을 지원할 수 있습니다.',
    footerDescriptor: 'Independent Market Structure Research', footerStatement: 'SkrrrrLabs는 독립 리서치 프로젝트입니다. 이 웹사이트의 내용은 투자 조언, 금융 조언 또는 미래 성과 보장이 아닙니다.', footerLinks: { process: '연구 과정', status: '연구 현황', markets: '연구 범위', about: '소개', collaboration: '협업', platforms: '트레이딩 플랫폼', risk: '위험 고지', affiliate: '제휴 고지', privacy: '개인정보', terms: '이용약관', contact: '문의' },
  },
};

Object.keys(copy).forEach((lang) => {
  copy[lang].platforms = exchanges.map((exchange) => ({ ...exchange, detail: exchange.detail[lang] }));
});
